# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='created_time',
            new_name='create_time',
        ),
    ]
